<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.otxHMth' shared service.

return $this->privates['.service_locator.otxHMth'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'networkRepo' => ['privates', 'App\\Repository\\NetworkRepository', 'getNetworkRepositoryService.php', true],
    'repo' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService.php', true],
    'repoPrice' => ['privates', 'App\\Repository\\PricingRepository', 'getPricingRepositoryService.php', true],
    'repoSub' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService.php', true],
], [
    'em' => '?',
    'networkRepo' => 'App\\Repository\\NetworkRepository',
    'repo' => 'App\\Repository\\ServicesRepository',
    'repoPrice' => 'App\\Repository\\PricingRepository',
    'repoSub' => 'App\\Repository\\SubscriptionRepository',
]);
