<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDDHP88s\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDDHP88s/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDDHP88s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDDHP88s\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDDHP88s\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DDHP88s',
    'container.build_id' => '7781e8f2',
    'container.build_time' => 1641388948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDDHP88s');
