<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jtYSKAW' shared service.

return $this->privates['.service_locator.jtYSKAW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'factRepo' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'subrepo' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService.php', true],
], [
    'em' => '?',
    'factRepo' => 'App\\Repository\\FactureRepository',
    'paginator' => '?',
    'subrepo' => 'App\\Repository\\SubscriptionRepository',
]);
