<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2vsZ9O4' shared service.

return $this->privates['.service_locator.2vsZ9O4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'subRepo' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService.php', true],
], [
    'subRepo' => 'App\\Repository\\SubscriptionRepository',
]);
