<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kxF3DuI' shared service.

return $this->privates['.service_locator.kxF3DuI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'factrepo' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService.php', true],
    'facture' => ['privates', '.errored..service_locator.kxF3DuI.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.kxF3DuI": it references class "App\\Entity\\Facture" but no such service exists.'],
    'subrepo' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService.php', true],
], [
    'factrepo' => 'App\\Repository\\FactureRepository',
    'facture' => 'App\\Entity\\Facture',
    'subrepo' => 'App\\Repository\\SubscriptionRepository',
]);
