<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.S4Kf9mh' shared service.

return $this->privates['.service_locator.S4Kf9mh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'servRepo' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService.php', true],
], [
    'em' => '?',
    'servRepo' => 'App\\Repository\\ServicesRepository',
]);
